/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Header */

#ifndef _Included_Header
#define _Included_Header
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Header
 * Method:    a
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Header_a
  (JNIEnv *, jclass);

/*
 * Class:     Header
 * Method:    b
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Header_b
  (JNIEnv *, jobject);

/*
 * Class:     Header
 * Method:    c
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Header_c
  (JNIEnv *, jclass);

/*
 * Class:     Header
 * Method:    d
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_Header_d
  (JNIEnv *, jobject, jint);

/*
 * Class:     Header
 * Method:    e
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_Header_e
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
