/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class InstanceAccess */

#ifndef _Included_InstanceAccess
#define _Included_InstanceAccess
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     InstanceAccess
 * Method:    propertyAccess
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_InstanceAccess_propertyAccess
  (JNIEnv *, jobject);

/*
 * Class:     InstanceAccess
 * Method:    methodAccess
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_InstanceAccess_methodAccess
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
