/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class HelloName */

#ifndef _Included_HelloName
#define _Included_HelloName
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     HelloName
 * Method:    sayHelloName
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_HelloName_sayHelloName
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
