/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ExceptionInNative */

#ifndef _Included_ExceptionInNative
#define _Included_ExceptionInNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ExceptionInNative
 * Method:    throwException
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ExceptionInNative_throwException
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
