/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_marakana_jniexamples_ArrayReader */

#ifndef _Included_com_marakana_jniexamples_ArrayReader
#define _Included_com_marakana_jniexamples_ArrayReader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_marakana_jniexamples_ArrayReader
 * Method:    sumArray
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_com_marakana_jniexamples_ArrayReader_sumArray
  (JNIEnv *, jclass, jintArray);

#ifdef __cplusplus
}
#endif
#endif
