/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class GetHello */

#ifndef _Included_GetHello
#define _Included_GetHello
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     GetHello
 * Method:    sayHi
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_GetHello_sayHi
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
